--CREATE USER WEHUB IDENTIFIED BY WEHUB;
--GRANT RESOURCE, CONNECT TO WEHUB;

--MEMBER 테이블
CREATE TABLE MEMBER (
    USER_NO NUMBER PRIMARY KEY,
    USER_COMPANYNAME VARCHAR2(30) NULL,
    USER_ID VARCHAR2(20) NOT NULL,
    USER_PWD VARCHAR2(100) NOT NULL,
    USER_NAME VARCHAR2(20) NOT NULL,  
    RANK VARCHAR2(15) NULL,
    EMAIL VARCHAR2(30) NULL,
    COMCALL VARCHAR2(20) NULL,
    PHONE VARCHAR2(20) NULL,
    ADDRESS VARCHAR2(80) NULL,
    USER_STATUS VARCHAR2(1) DEFAULT 'Y' CHECK(USER_STATUS IN('Y', 'N')),
    DEPT_CODE VARCHAR2(10) NULL
);
-- USER_COMPANYNUMBER VARCHAR2(20) NOT NULL,
--DROP TABLE MEMBER;
--DROP SEQUENCE SEQ_USER_NO;
--ALTER TABLE MEMBER DROP COLUMN CREATE_DATE;
--ALTER TABLE MEMBER DROP COLUMN MODIFY_DATE;
--ALTER TABLE MEMBER MODIFY RANK VARCHAR2(15);
--ALTER TABLE MEMBER RENAME COLUMN COMPANY_RANK TO RANK;

--ALTER TABLE MEMBER MODIFY USER_COMPANYNAME VARCHAR2(40);
ALTER TABLE MEMBER MODIFY ADDRESS VARCHAR2(100);

COMMENT ON COLUMN MEMBER.USER_NO IS '회원번호';
COMMENT ON COLUMN MEMBER.USER_COMPANYNAME IS '회사명';
COMMENT ON COLUMN MEMBER.USER_ID IS '회원아이디';
COMMENT ON COLUMN MEMBER.USER_PWD IS '회원비밀번호';
COMMENT ON COLUMN MEMBER.USER_NAME IS '회원이름';
COMMENT ON COLUMN MEMBER.RANK IS '직급';
COMMENT ON COLUMN MEMBER.EMAIL IS '이메일';
COMMENT ON COLUMN MEMBER.COMCALL IS '내선번호';
COMMENT ON COLUMN MEMBER.PHONE IS '휴대번호';
COMMENT ON COLUMN MEMBER.ADDRESS IS '거주지';
COMMENT ON COLUMN MEMBER.USER_STATUS IS '회원상태값(Y/N)';
COMMENT ON COLUMN MEMBER.DEPT_CODE IS '부서코드';

CREATE SEQUENCE SEQ_USER_NO;

INSERT INTO MEMBER VALUES(
    SEQ_USER_NO.NEXTVAL,'WEHUB','admin','1234','관리자','부장','admin@wehub.com','0211112222','01011112222','서울시 강남구 역삼동',DEFAULT,NULL
);
INSERT INTO MEMBER (
			USER_NO,
			USER_COMPANYNAME,
			USER_ID,
			USER_PWD,
			USER_NAME,
			RANK,
			EMAIL,
			COMCALL,
			PHONE,
			ADDRESS,
			USER_STATUS,
			DEPT_CODE,
			USER_IMG_ORIFILENAME,
			USER_IMG_REFILENAME
		)
		VALUES(
			SEQ_USER_NO.NEXTVAL, 
			'TEst', 
			'test', 
			1234, 
			'테스트',
			'사원', 
			'123@b.b', 
			02123, 
			0101234, 
			'null', 
			DEFAULT, 
			'null',
			'null',
			'null'
		);

-- 멤버 추가
-- INSERT INTO MEMBER VALUES(SEQ_USER_NO.NEXTVAL,#{},#{},#{},#{},#{},#{},#{},#{},#{},'Y',NULL)
-- INSERT INTO MEMBER VALUES(SEQ_USER_NO.NEXTVAL,#{},#{},#{},#{},#{},#{},#{},#{},#{},SYSDATE,SYSDATE,'Y',NULL)

COMMIT;

-- DEPARTMENT 테이블
CREATE TABLE DEPARTMENT (
    DEPT_CODE VARCHAR2(10) NULL,
    DEPT_NAME VARCHAR2(20) NULL
);

COMMENT ON COLUMN DEPARTMENT.DEPT_CODE IS '부서코드';
COMMENT ON COLUMN DEPARTMENT.DEPT_NAME IS '부서명';
--DROP TABLE DEPARTMENT;

COMMIT;
    
    
-- 프로필 이미지 테이블
CREATE TABLE MEMBER_IMAGE_FILE (
    MEM_IMG_NO NUMBER PRIMARY KEY,
    USER_NO VARCHAR2(30) NOT NULL,
    MEM_IMG_PATH VARCHAR2(20) NULL,
    MEM_IMG_ORG VARCHAR2(100) NULL,
    MEM_IMG_SAV VARCHAR2(20) NULL,  
    MEM_IMG_DATE DATE DEFAULT SYSDATE
);

COMMENT ON COLUMN MEMBER_IMAGE_FILE.MEM_IMG_NO IS '파일번호시퀀스';
COMMENT ON COLUMN MEMBER_IMAGE_FILE.USER_NO IS '사번';
COMMENT ON COLUMN MEMBER_IMAGE_FILE.MEM_IMG_PATH IS '저장경로';
COMMENT ON COLUMN MEMBER_IMAGE_FILE.MEM_IMG_ORG IS '원본파일이름';
COMMENT ON COLUMN MEMBER_IMAGE_FILE.MEM_IMG_SAV IS '저장파일이름';
COMMENT ON COLUMN MEMBER_IMAGE_FILE.MEM_IMG_DATE IS '등록일';

CREATE SEQUENCE SEQ_MEM_IMG_NO;

--UPDATE MEMBER SET USER_PWD=${} WHERE USER_ID=${};

ALTER TABLE MEMBER ADD USER_IMG_ORIFILENAME VARCHAR2(100) NULL; 
ALTER TABLE MEMBER ADD USER_IMG_REFILENAME VARCHAR2(100) NULL;

COMMENT ON COLUMN MEMBER.USER_IMG_ORIFILENAME IS '프로필이미지원본파일명';
COMMENT ON COLUMN MEMBER.USER_IMG_REFILENAME IS '프로필이미지수정파일명';

INSERT INTO MEMBER VALUES(
    SEQ_USER_NO.NEXTVAL,'WEHUB','testImg','1234','테스트','부장','1234@wehub.com','0211112222','01011112222','서울시 강남구 역삼동',DEFAULT,'개발팀',NULL,NULL
);


ALTER TABLE MEMBER DROP COLUMN CREATE_DATE;
ALTER TABLE MEMBER DROP COLUMN MODIFY_DATE;

COMMIT;


------------------------------------ Approval ------------------------------------
------------------------------------  전자결재  -----------------------------------
CREATE TABLE APPROVAL (
    APP_SEQ NUMBER PRIMARY KEY,
    APP_WRITE_SYS DATE DEFAULT SYSDATE,
    FIRST_TIME_APPROVER VARCHAR2(20) NULL,
    INTERIM_APPROVER VARCHAR2(20) NULL,
    FINAL_APPROVER VARCHAR2(20) NULL,
    APP_CHECK_SYSDATE DATE NULL,
    APP_CHECK_PROGRESS VARCHAR2(30) NULL,
    APP_REASON VARCHAR2(30) NULL,
    APP_ORIFILENAME VARCHAR2(100) NULL, 
    APP_REFILENAME VARCHAR2(100) NULL,
    USER_NO NUMBER NOT NULL
);

CREATE SEQUENCE SEQ_APP_SEQ;

COMMENT ON COLUMN APPROVAL.APP_SEQ IS '전자결재시퀀스';
COMMENT ON COLUMN APPROVAL.APP_WRITE_SYS IS '작성일자';
COMMENT ON COLUMN APPROVAL.FIRST_TIME_APPROVER IS '최초승인자';
COMMENT ON COLUMN APPROVAL.INTERIM_APPROVER IS '중간승인자';
COMMENT ON COLUMN APPROVAL.FINAL_APPROVER IS '최종승인자';
COMMENT ON COLUMN APPROVAL.APP_CHECK_SYSDATE IS '결재일시';
COMMENT ON COLUMN APPROVAL.APP_CHECK_PROGRESS IS '결재상태';
COMMENT ON COLUMN APPROVAL.APP_REASON IS '반려사유';
COMMENT ON COLUMN APPROVAL.APP_ORIFILENAME IS '증빙원본파일명';
COMMENT ON COLUMN APPROVAL.APP_REFILENAME IS '증빙수정파일명';
COMMENT ON COLUMN APPROVAL.APP_WRITER_NO IS '작성자';

-- INSRET 
INSERT INTO APPROVAL VALUES(
    SEQ_APP_SEQ.NEXTVAL,SYSDATE,'최초승인자','중간승인자','최종승인자',SYSDATE,'미결',NULL,NULL,NULL,2
);

------------------------------------ Letter Of Approval ------------------------------------
------------------------------------      품의서 양식     ------------------------------------
CREATE TABLE APP_LOA (
    LOA_SEQ NUMBER PRIMARY KEY,
    LOA_APP_SEQ NUMBER NOT NULL,
    LOA_TITLE VARCHAR2(100) NULL,
    LOA_DETAIL VARCHAR2(1000) NULL,
    LOA_STATUS VARCHAR2(1) DEFAULT 'Y' CHECK(LOA_STATUS IN('Y', 'N')),
    LOA_PRESENT VARCHAR2(3) DEFAULT 'A' CHECK(LOA_PRESENT IN ('A', 'B', 'C')),
    CONSTRAINT FK_LOA_APP_SEQ FOREIGN KEY(LOA_APP_SEQ) REFERENCES APPROVAL(APP_SEQ) ON DELETE SET NULL
);

CREATE SEQUENCE SEQ_LOA_SEQ;

COMMENT ON COLUMN APP_LOA.LOA_SEQ IS '품의서고유번호';
COMMENT ON COLUMN APP_LOA.LOA_TITLE IS '제목';
COMMENT ON COLUMN APP_LOA.LOA_DETAIL IS '상세내용';
COMMENT ON COLUMN APP_LOA.LOA_STATUS IS '문서상태';
COMMENT ON COLUMN APP_LOA.LOA_PRESENT IS '결재현황';
COMMENT ON COLUMN APP_LOA.LOA_APP_SEQ IS '전자결재시퀀스';

------------------------------------ Leave Application ------------------------------------
------------------------------------   휴가신청서 양식   ------------------------------------
CREATE TABLE APP_LEAVE (
    LEAVE_SEQ NUMBER PRIMARY KEY,
    LEAVE_APP_SEQ NUMBER NOT NULL,
    LEAVE_CLASSIFY VARCHAR2(30) NULL,
    LEAVE_START DATE NULL,
    LEAVE_FINISH DATE NULL,
    LEAVE_DETAIL VARCHAR2(1000) NULL,
    LEAVE_STATUS VARCHAR2(1) DEFAULT 'Y' CHECK(LEAVE_STATUS IN('Y', 'N')),
    LEAVE_PRESENT VARCHAR2(3) DEFAULT 'A' CHECK(LEAVE_PRESENT IN ('A', 'B', 'C')),
    CONSTRAINT FK_LEAVE_APP_SEQ FOREIGN KEY(LEAVE_APP_SEQ) REFERENCES APPROVAL(APP_SEQ) ON DELETE SET NULL
);

CREATE SEQUENCE SEQ_LEAVE_SEQ;

COMMENT ON COLUMN APP_LEAVE.LEAVE_SEQ IS '휴가신청서고유번호';
COMMENT ON COLUMN APP_LEAVE.LEAVE_APP_SEQ IS '전자결재시퀀스';
COMMENT ON COLUMN APP_LEAVE.LEAVE_CLASSIFY IS '휴가구분';
COMMENT ON COLUMN APP_LEAVE.LEAVE_START IS '휴가시작';
COMMENT ON COLUMN APP_LEAVE.LEAVE_FINISH IS '휴가종료';
COMMENT ON COLUMN APP_LEAVE.LEAVE_DETAIL IS '세부사항(사유)';
COMMENT ON COLUMN APP_LEAVE.LEAVE_STATUS IS '문서상태';
COMMENT ON COLUMN APP_LEAVE.LEAVE_PRESENT IS '결재현황'; --LEAVE_PRESENT(A'접수승인',  B'접수',  C'접수반려')

ALTER TABLE APP_LEAVE MODIFY APP_LEAVE_CALL VARCHAR2(20) NULL;

-- INSRET 
INSERT INTO APP_LEAVE VALUES(
    SEQ_LEAVE_SEQ.NEXTVAL,1,'병가',SYSDATE,SYSDATE,'건강검진',DEFAULT,DEFAULT
);
ALTER TABLE APP_LEAVE MODIFY LEAVE_START VARCHAR2(10);
ALTER TABLE APP_LEAVE MODIFY LEAVE_FINISH VARCHAR2(10);
ALTER TABLE APP_LEAVE MODIFY APP_EMERGENCYCALL VARCHAR2(20);
------------------------------------ Expense Report ------------------------------------
------------------------------------  지출결의서 양식  -----------------------------------
CREATE TABLE APP_ER (
    ER_SEQ NUMBER PRIMARY KEY,
    ER_APP_SEQ NUMBER NOT NULL,
    ER_DEADLINE DATE NULL,
    ER_CLASSIFY VARCHAR2(30) NULL,
    ER_TITLE VARCHAR2(100) NULL,
    ER_DETAIL VARCHAR2(1000) NULL,
    ER_AMOUNT VARCHAR2(20) NULL,
    ER_REFERENCE VARCHAR2(100) DEFAULT ' ',
    ER_STATUS VARCHAR2(1) DEFAULT 'Y' CHECK(ER_STATUS IN('Y', 'N')),
    ER_PRESENT VARCHAR2(3) DEFAULT 'A' CHECK(ER_PRESENT IN ('A', 'B', 'C')),
    CONSTRAINT FK_ER_APP_SEQ FOREIGN KEY(ER_APP_SEQ) REFERENCES APPROVAL(APP_SEQ) ON DELETE SET NULL
);

CREATE SEQUENCE SEQ_ER_SEQ;

COMMENT ON COLUMN APP_ER.ER_SEQ IS '지출결의서고유번호';
COMMENT ON COLUMN APP_ER.ER_APP_SEQ IS '전자결재시퀀스';
COMMENT ON COLUMN APP_ER.ER_DEADLINE IS '지급요청일자';
COMMENT ON COLUMN APP_ER.ER_CLASSIFY IS '계정과목';
COMMENT ON COLUMN APP_ER.ER_TITLE IS '제목';
COMMENT ON COLUMN APP_ER.ER_DETAIL IS '적요';
COMMENT ON COLUMN APP_ER.ER_AMOUNT IS '금액';
COMMENT ON COLUMN APP_ER.ER_REFERENCE IS '비고';
COMMENT ON COLUMN APP_ER.ER_STATUS IS '문서상태';
COMMENT ON COLUMN APP_ER.ER_PRESENT IS '결재상태';
    
------------------------------------ Expense Report ------------------------------------
------------------------------------   수신참조내역   ------------------------------------
CREATE TABLE APP_RECEIVE_REF (
    RECEIVE_REF_SEQ NUMBER PRIMARY KEY,
    RECEIVE_REF_APP_SEQ NUMBER NOT NULL,
    RECEIVE_REF_CC VARCHAR2(30) NULL,
    CONSTRAINT FK_RECEIVE_REF_APP_SEQ FOREIGN KEY(RECEIVE_REF_APP_SEQ) REFERENCES APPROVAL(APP_SEQ) ON DELETE SET NULL
);

CREATE SEQUENCE SEQ_RECEIVE_REF_SEQ;

COMMENT ON COLUMN APP_RECEIVE_REF.RECEIVE_REF_SEQ IS '수신참조고유번호';
COMMENT ON COLUMN APP_RECEIVE_REF.RECEIVE_REF_APP_SEQ IS '전자결재시퀀스';
COMMENT ON COLUMN APP_RECEIVE_REF.RECEIVE_REF_CC IS '수신참조자';
    
COMMIT;    

alter table approval add APP_WRITER_NO number not null;
alter table approval drop column user_no;
alter table app_leave add APP_EMERGENCYCALL number not null;
COMMENT ON COLUMN APP_LEAVE.APP_EMERGENCYCALL IS '비상연락망';
ALTER TABLE approval DROP COLUMN app_check_progress;
alter table approval add APP_CHECK_PROGRESS VARCHAR2(20) DEFAULT '결재대기' CHECK(APP_CHECK_PROGRESS IN ('결재대기', '결재중', '결재완료'));
COMMENT ON COLUMN APPROVAL.APP_CHECK_PROGRESS IS '결재상태';
COMMIT;
alter table approval add APPROVAL_KINDS varchar2(30) null;
COMMENT ON COLUMN approval.approval_kinds IS '결재종류';

-- 04/11 update
ALTER TABLE APP_LEAVE MODIFY LEAVE_START VARCHAR2(10);
ALTER TABLE APP_LEAVE MODIFY LEAVE_FINISH VARCHAR2(10);
ALTER TABLE APP_LEAVE MODIFY APP_EMERGENCYCALL VARCHAR2(20);