CREATE TABLE CALENDAR (
	CAL_NO	NUMBER	NOT NULL,
	USER_NO	NUMBER	NOT NULL,
	CAL_YEAR	VARCHAR2(5)	NOT NULL,
	CAL_MONTH	VARCHAR2(3)	NOT NULL,
	CAL_DAY	VARCHAR2(3)	NOT NULL,
	CAL_CONTENT	VARCHAR2(1000)	NULL,
	CAL_DATE DATE DEFAULT SYSDATE
);

ALTER TABLE calendar ADD CONSTRAINT PK_CALENDAR PRIMARY KEY (
	CAL_NO
);

CREATE SEQUENCE SEQ_CAL_NO;

INSERT INTO CALENDAR VALUES(
    SEQ_CAL_NO.NEXTVAL,
    21,
    2021,
    3,
    28,
    '데이터일요일',
    SYSDATE
);

SELECT M.USER_NO, C.CAL_CONTENT, C.CAL_DATE
FROM CALENDAR C
JOIN MEMBER M ON(M.USER_NO = C.USER_NO)
WHERE M.USER_NO = 21;

commit;

UPDATE CALENDAR
		SET
			CAL_CONTENT='일요일데이터2',
			CAL_DATE=SYSDATE
		WHERE
			CAL_NO = 8;
------------------------------------------------------------

--커뮤니티 테이블 생성
CREATE TABLE COMMUNITY (
	CM_NO	NUMBER	NOT NULL,
	USER_NO	NUMBER	NOT NULL,
	CM_TITLE	VARCHAR2(300)	NULL,
	CM_CONTENT	VARCHAR2(1000)	NULL,
	CM_READCOUNT	NUMBER	NULL,
	CM_DATE	 DATE	DEFAULT SYSDATE,
	CM_MODIFY_DATE	DATE	DEFAULT SYSDATE,
	CM_STATUS	CHAR(1)	DEFAULT 'Y' CHECK(CM_STATUS IN('Y','N','F'))
);

ALTER TABLE COMMUNITY ADD CONSTRAINT PK_COMMUNITY PRIMARY KEY (
	CM_NO
);
CREATE SEQUENCE SEQ_CM_NO;

ALTER TABLE COMMUNITY ADD CONSTRAINT FK_MEMBER_TO_Community_1 FOREIGN KEY (
	USER_NO
)
REFERENCES MEMBER (
	USER_NO
);

INSERT INTO COMMUNITY VALUES(
    SEQ_CM_NO.NEXTVAL,
    22,
    '제주 항공권 00월 00일 반값에..',
    '안녕하세요',
    4,
    '21/04/08',
    '21/04/08',
    'Y'
);

COMMIT;

SELECT C.CM_NO, M.USER_ID, C.USER_NO, C.CM_TITLE, C.CM_CONTENT, C.CM_READCOUNT, C.CM_DATE, C.CM_MODIFY_DATE, C.CM_STATUS
FROM COMMUNITY C
JOIN MEMBER M ON (M.USER_NO = C.USER_NO)
ORDER BY CM_DATE DESC;

SELECT C.CM_NO,
		C.USER_NO,
		M.USER_NAME, 
		C.CM_TITLE, 
		C.CM_CONTENT, 
		C.CM_READCOUNT, 
		C.CM_DATE, 
		C.CM_MODIFY_DATE, 
		C.CM_STATUS
		FROM COMMUNITY C
		JOIN MEMBER M ON (M.USER_NO = C.USER_NO)
        WHERE CM_NO = 46
		ORDER BY C.CM_DATE DESC;
        
        COMMIT;
        
        
CREATE TABLE CM_BOOKMARK (
	CM_BM_NO	NUMBER	NOT NULL,
	USER_NO	NUMBER	NOT NULL,
	CM_NO	NUMBER	NOT NULL
);

ALTER TABLE CM_BOOKMARK ADD CONSTRAINT PK_CM_BOOKMARK PRIMARY KEY (
	CM_BM_NO
);

CREATE SEQUENCE SEQ_BM_NO;

ALTER TABLE CM_BOOKMARK ADD CONSTRAINT FK_MEMBER_CM_BOOKMARK FOREIGN KEY (
	USER_NO
)
REFERENCES MEMBER (
	USER_NO
);

ALTER TABLE CM_BOOKMARK ADD CONSTRAINT FK_Community_CM_BOOKMARK FOREIGN KEY (
	CM_NO
)
REFERENCES Community (
	CM_NO
);
