CREATE TABLE CALENDAR (
	CAL_NO	NUMBER	NOT NULL,
	USER_NO	NUMBER	NOT NULL,
	CAL_YEAR	VARCHAR2(5)	NOT NULL,
	CAL_MONTH	VARCHAR2(3)	NOT NULL,
	CAL_DAY	VARCHAR2(3)	NOT NULL,
	CAL_CONTENT	VARCHAR2(1000)	NULL,
	CAL_DATE DATE DEFAULT SYSDATE
);

ALTER TABLE calendar ADD CONSTRAINT PK_CALENDAR PRIMARY KEY (
	CAL_NO
);

CREATE SEQUENCE SEQ_CAL_NO;

INSERT INTO CALENDAR VALUES(
    SEQ_CAL_NO.NEXTVAL,
    21,
    2021,
    3,
    28,
    '데이터일요일',
    SYSDATE
);

SELECT M.USER_NO, C.CAL_CONTENT, C.CAL_DATE
FROM CALENDAR C
JOIN MEMBER M ON(M.USER_NO = C.USER_NO)
WHERE M.USER_NO = 21;

commit;
